'use client';

import { useState, useTransition, useEffect } from 'react';
import { generateInsight } from '@/app/actions/insight';
import { Sparkles, CheckCircle2, AlertCircle, AlertTriangle, RefreshCw } from 'lucide-react';

export default function InsightClient({
  eventId,
  initialInsight,
  hasResponses,
}: {
  eventId: string;
  initialInsight: any;
  hasResponses: boolean;
}) {
  const [insight, setInsight] = useState(initialInsight);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (!insight && hasResponses && !hasAutoGenerated && !isPending && !error) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
  }, [insight, hasResponses, hasAutoGenerated, isPending, error]);

  const handleGenerate = () => {
    setError(null);
    startTransition(async () => {
      const res = await generateInsight(eventId);
      if (res?.error) {
        setError(res.error);
      } else {
        window.location.reload();
      }
    });
  };

  return (
    <div className="surface-card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            width: '28px',
            height: '28px',
            borderRadius: '50%',
            backgroundColor: 'var(--accent-pink-pastel)',
            color: 'var(--accent-pink-hot)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
            <Sparkles size={15} strokeWidth={2} />
          </div>
          <h3 style={{ fontSize: '16px', fontWeight: '800', margin: 0, color: 'var(--text-primary)' }}>
            AI Intelligence Summary
          </h3>
        </div>

        <button
          onClick={handleGenerate}
          className="btn-cta"
          disabled={isPending || !hasResponses}
          style={{
            padding: '6px 14px',
            fontSize: '12px',
            minHeight: '34px',
            opacity: hasResponses ? 1 : 0.5,
            cursor: hasResponses ? 'pointer' : 'not-allowed',
          }}
        >
          {isPending ? (
            <span>กำลังวิเคราะห์...</span>
          ) : (
            <>
              <RefreshCw size={13} strokeWidth={2} className={isPending ? 'spin' : ''} />
              <span>{insight ? 'อัปเดต AI' : 'วิเคราะห์ AI'}</span>
            </>
          )}
        </button>
      </div>

      {error && (
        <div style={{
          padding: '12px 16px',
          background: 'rgba(239, 68, 68, 0.08)',
          color: 'var(--status-danger)',
          borderRadius: 'var(--radius-md)',
          border: '1px solid rgba(239, 68, 68, 0.2)',
          fontSize: '13px',
          fontWeight: '600',
          marginBottom: '16px',
        }}>
          ⚠️ {error}
        </div>
      )}

      {!insight && !isPending && !error && (
        <div style={{
          textAlign: 'center',
          padding: '32px 20px',
          color: 'var(--text-secondary)',
          background: 'rgba(255, 255, 255, 0.75)',
          borderRadius: 'var(--radius-card)',
          border: '2px dashed rgba(232, 70, 124, 0.25)',
        }}>
          <div style={{ marginBottom: '14px', display: 'flex', justifyContent: 'center' }}>
            <div
              className="float-animation"
              style={{
                width: '124px',
                height: '124px',
                borderRadius: '28px',
                overflow: 'hidden',
                boxShadow: '0 8px 24px rgba(232, 70, 124, 0.15)',
                border: '2px solid rgba(255, 209, 227, 0.8)',
                backgroundColor: '#FFFFFF',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <img
                src="/images/cute-waiting-mascot.jpg"
                alt="น้อง AI มารอคำตอบ"
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                }}
              />
            </div>
          </div>

          <h4 style={{ fontSize: '16px', fontWeight: '800', marginBottom: '6px', color: 'var(--text-primary)' }}>
            {hasResponses ? 'น้อง AI พร้อมสรุปข้อมูลให้คุณแล้ว' : 'กำลังรอเสียงตอบรับจากผู้ร่วมงาน'}
          </h4>
          <p style={{ fontSize: '13px', margin: 0, maxWidth: '320px', marginInline: 'auto', lineHeight: 1.5, color: 'var(--text-secondary)' }}>
            {hasResponses
              ? 'กดปุ่ม "วิเคราะห์ AI" เพื่อให้ปัญญาประดิษฐ์สรุปใจความสำคัญจากทุกคำตอบ'
              : 'เมื่อมีผู้เริ่มสแกนตอบแบบสอบถาม ระบบจะช่วยสรุปฟีดแบ็กให้อัตโนมัติทันที'}
          </p>
        </div>
      )}

      {insight && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {/* ภาพรวม / Overview */}
          <div style={{
            padding: '16px',
            backgroundColor: 'rgba(230, 220, 250, 0.35)',
            borderRadius: 'var(--radius-md)',
            border: '1px solid rgba(230, 220, 250, 0.7)',
          }}>
            <h4 style={{ fontSize: '13px', fontWeight: '800', color: '#5B4B8A', marginBottom: '4px' }}>
              💡 ภาพรวมความคิดเห็น
            </h4>
            <p style={{ fontSize: '13px', color: 'var(--text-primary)', lineHeight: '1.5', margin: 0 }}>
              {insight.whyScore}
            </p>
          </div>

          {/* Keep: Mint Green Card */}
          <div style={{
            padding: '16px',
            backgroundColor: 'var(--badge-mint)',
            borderRadius: 'var(--radius-md)',
            border: '1px solid rgba(213, 240, 208, 0.8)',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
              <CheckCircle2 size={16} color="var(--badge-mint-text)" strokeWidth={2} />
              <h4 style={{ fontSize: '13px', fontWeight: '800', color: 'var(--badge-mint-text)', margin: 0 }}>
                Keep (สิ่งที่ทำได้ดีแล้ว)
              </h4>
            </div>
            <p style={{ fontSize: '13px', color: '#1B541A', lineHeight: '1.5', margin: 0 }}>
              {insight.keep}
            </p>
          </div>

          {/* Improve: Pale Yellow Card */}
          <div style={{
            padding: '16px',
            backgroundColor: 'var(--badge-yellow)',
            borderRadius: 'var(--radius-md)',
            border: '1px solid rgba(255, 243, 184, 0.8)',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
              <AlertCircle size={16} color="var(--badge-yellow-text)" strokeWidth={2} />
              <h4 style={{ fontSize: '13px', fontWeight: '800', color: 'var(--badge-yellow-text)', margin: 0 }}>
                Improve (สิ่งที่ควรปรับปรุง)
              </h4>
            </div>
            <p style={{ fontSize: '13px', color: '#6A5610', lineHeight: '1.5', margin: 0 }}>
              {insight.improve}
            </p>
          </div>

          {/* Fix: Pastel Rose Card */}
          <div style={{
            padding: '16px',
            backgroundColor: 'var(--badge-pink)',
            borderRadius: 'var(--radius-md)',
            border: '1px solid rgba(255, 226, 238, 0.9)',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
              <AlertTriangle size={16} color="var(--badge-pink-text)" strokeWidth={2} />
              <h4 style={{ fontSize: '13px', fontWeight: '800', color: 'var(--badge-pink-text)', margin: 0 }}>
                Fix (ปัญหาที่ต้องแก้ไขด่วน)
              </h4>
            </div>
            <p style={{ fontSize: '13px', color: '#9E1C48', lineHeight: '1.5', margin: 0 }}>
              {insight.fix}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
