'use client';

import { useState, useTransition, useEffect } from 'react';
import { generateInsight } from '@/app/actions/insight';

export default function InsightClient({ eventId, initialInsight, hasResponses }: { eventId: string, initialInsight: any, hasResponses: boolean }) {
  const [insight, setInsight] = useState(initialInsight);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (!insight && hasResponses && !hasAutoGenerated && !isPending && !error) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
  }, [insight, hasResponses, hasAutoGenerated, isPending, error]);

  const handleGenerate = () => {
    setError(null);
    startTransition(async () => {
      const res = await generateInsight(eventId);
      if (res?.error) {
        setError(res.error);
      } else {
        window.location.reload();
      }
    });
  };

  return (
    <div className="glass-card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <h3 style={{ margin: 0 }}>AI Intelligence Summary</h3>
        <button
          onClick={handleGenerate}
          className="btn-primary"
          disabled={isPending || !hasResponses}
          style={{
            padding: '8px 16px',
            fontSize: '0.9rem',
            opacity: hasResponses ? 1 : 0.5,
            cursor: hasResponses ? 'pointer' : 'not-allowed'
          }}
        >
          {isPending ? 'กำลังวิเคราะห์ AI...' : (insight ? 'อัปเดตผลวิเคราะห์ใหม่' : 'สร้างผลวิเคราะห์ (AI)')}
        </button>
      </div>

      {error && (
        <div style={{ padding: '12px', background: 'rgba(239, 68, 68, 0.1)', color: 'var(--danger)', borderLeft: '4px solid var(--danger)', marginBottom: '16px' }}>
          {error}
        </div>
      )}

      {!insight && !isPending && !error && (
        <div style={{
          textAlign: 'center',
          padding: '60px 20px',
          color: 'var(--text-muted)',
          background: 'var(--card-bg)',
          borderRadius: '16px',
          border: '2px dashed var(--card-border)',
          marginTop: '16px'
        }}>
          <div style={{ fontSize: '4rem', marginBottom: '16px', animation: 'float 3s ease-in-out infinite', display: 'inline-block', textShadow: '0 5px 15px rgba(0,0,0,0.05)' }}>
            {hasResponses ? '🤖✨' : '🤖💤'}
          </div>
          <h4 style={{ marginBottom: '8px', color: 'var(--text-main)', fontSize: '1.3rem' }}>
            {hasResponses ? 'น้อง AI พร้อมทำงานแล้ว!' : 'น้อง AI กำลังสแตนด์บายรอข้อมูลอยู่'}
          </h4>
          <p style={{ margin: 0, maxWidth: '400px', marginInline: 'auto', lineHeight: 1.6 }}>
            {hasResponses
              ? 'คลิกที่ปุ่มด้านบนเพื่อปลุกน้อง AI มาช่วยสรุปฟีดแบ็กทั้งหมดให้คุณ'
              : 'เมื่อมีผู้เริ่มสแกนตอบแบบสอบถาม น้องจะตื่นมาวิเคราะห์ให้คุณแบบอัตโนมัติทันที!'}
          </p>
        </div>
      )}

      {insight && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '16px' }}>
          <div style={{ padding: '16px', borderLeft: '4px solid var(--text-muted)', background: 'rgba(0,0,0,0.02)', borderRadius: '0 8px 8px 0' }}>
            <h4 style={{ marginBottom: '8px' }}>ภาพรวม</h4>
            <p>{insight.whyScore}</p>
          </div>

          <div style={{ padding: '16px', borderLeft: '4px solid #10b981', background: 'rgba(16, 185, 129, 0.05)', borderRadius: '0 8px 8px 0' }}>
            <h4 style={{ marginBottom: '8px', color: '#047857' }}>Keep (สิ่งที่ทำได้ดีแล้ว)</h4>
            <p>{insight.keep}</p>
          </div>

          <div style={{ padding: '16px', borderLeft: '4px solid #f59e0b', background: 'rgba(245, 158, 11, 0.05)', borderRadius: '0 8px 8px 0' }}>
            <h4 style={{ marginBottom: '8px', color: '#b45309' }}>Improve (สิ่งที่ควรปรับปรุง)</h4>
            <p>{insight.improve}</p>
          </div>

          <div style={{ padding: '16px', borderLeft: '4px solid #ef4444', background: 'rgba(239, 68, 68, 0.05)', borderRadius: '0 8px 8px 0' }}>
            <h4 style={{ marginBottom: '8px', color: '#b91c1c' }}>Fix (ปัญหาที่ต้องแก้ไขด่วน)</h4>
            <p>{insight.fix}</p>
          </div>
        </div>
      )}
    </div>
  );
}
